# Assignment

Import numpy as np

In [1]:
import numpy as np 

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [5]:
a = [1,2,3,4,5]
a = np.array(a)
a

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [6]:
b = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(b)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [7]:
c = np.arange(1,18,2).reshape(3,3)
c

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [8]:
d = np.random.randint(low = 0, high = 10, size = 10)
d

array([3, 8, 8, 5, 1, 8, 2, 6, 5, 6])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [9]:
e = np.array([1,2,3,4,5])
e.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [12]:
e.shape

(5,)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [15]:
f = d = np.random.randint(low = 0, high = 10, size = 10)
print(f[2])
print(f[3])
print(f[8])

1
5
9


Print alternate elements of that array

In [19]:
f[::2]

array([4, 1, 1, 1, 9])

Change last 3 elements into 100 using broadcasting and print

In [21]:
f[-3:] = 100
f

array([  4,   4,   1,   5,   1,   5,   1, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [25]:
g = np.random.randint(low = 1, high = 25, size = 25).reshape(5,5)
print(g)
g[1:4,1:4]

[[ 7 14  5 20  8]
 [ 4  3  1 16 11]
 [ 1 10  2 13  3]
 [15 24  2  3 24]
 [18 24 12  5 24]]


array([[ 3,  1, 16],
       [10,  2, 13],
       [24,  2,  3]])